# Generated by Django 4.1.1 on 2022-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_remove_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product',
            field=models.CharField(choices=[('Workflow AI', 'Workflow AI'), ('Digital Q', 'Digital Q'), ('Wifi QR code', 'Wifi QR code')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
